services:
  windows:
    image: dockur/windows
    container_name: windows
    environment:
      VERSION: "tiny10"
      STARTUP: "powershell -ExecutionPolicy Bypass -File C:\\scripts\\setup_roblox.ps1"
    volumes:
      - ./scripts:/scripts
    ports:
      - 8006:8006
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    restart: on-failure
